import type { ZigbeeDevice } from './zigbeeTypes'

export const zigbeeDeviceConcepts: ZigbeeDevice[] = [
  {
    deviceId: 'sonoff-zbdongle-e',
    name: 'SONOFF ZBDongle-E',
    model: 'SONOFF ZBDongle-E',
    kind: 'coordinator',
    category: 'gateway',
    manufacturer: 'SONOFF',
    online: true,
    batteryLevel: null,
    batteryPowered: false,
    room: 'Teknisk',
    signalStrength: 96,
    protocol: 'zigbee',
    firmwareVersion: 'Foundation',
    pairedAt: '2026-05-11',
    lastSeen: 'Nylig',
    notes: 'Planlagt lokal Zigbee-koordinator. KNX forblir backbone, Zigbee brukes som edge/fleksibilitet.',
  },
  {
    deviceId: 'zigbee-sensor-concept',
    name: 'TV-stue Temperaturføler',
    model: 'Sensor-konsept',
    kind: 'sensor',
    category: 'climate',
    manufacturer: 'Foundation',
    online: false,
    batteryLevel: 78,
    batteryPowered: true,
    room: 'TV-stue',
    signalStrength: 62,
    protocol: 'zigbee',
    firmwareVersion: '0.1-foundation',
    pairedAt: '2026-05-11',
    lastSeen: 'Siste kjente',
    notes: 'For fremtidige temperatur-, bevegelse- og lekkasjesensorer.',
  },
  {
    deviceId: 'zigbee-switch-concept',
    name: 'ELKO Bryter Entré',
    model: 'Bryter-konsept',
    kind: 'switch',
    category: 'switch',
    manufacturer: 'ELKO',
    online: false,
    batteryLevel: 91,
    batteryPowered: true,
    room: 'Entré',
    signalStrength: 68,
    protocol: 'zigbee',
    firmwareVersion: '0.1-foundation',
    pairedAt: '2026-05-11',
    lastSeen: 'Siste kjente',
    notes: 'For fleksible lokale brytere uten å endre KNX-backbone.',
  },
  {
    deviceId: 'zigbee-motion-kitchen-concept',
    name: 'Kjøkken Bevegelsessensor',
    model: 'Motion-konsept',
    kind: 'sensor',
    category: 'sensor',
    manufacturer: 'Foundation',
    online: false,
    batteryLevel: 64,
    batteryPowered: true,
    room: 'Kjøkken',
    signalStrength: 43,
    protocol: 'zigbee',
    firmwareVersion: '0.1-foundation',
    pairedAt: '2026-05-11',
    lastSeen: 'Ukjent',
    notes: 'Foundation for bevegelse og presence fra edge-laget.',
  },
]
