export const sensitiveRuntimeCapabilities = new Set([
  'writeState',
  'executeAction',
  'providerLifecycle',
  'proposeAction',
  'diagnosticsAccess',
])

export const runtimeDomainDefinitions = [
  {
    domainId: 'climate',
    category: 'environment',
    displayName: 'Climate',
    runtimeOwner: 'knx-runtime',
    capabilities: ['readState', 'writeState', 'realtimeEvents', 'persistentHistory', 'polling', 'subscriptions', 'signalLogging'],
    providers: ['knx', 'mill', 'namron'],
    trustedActions: ['roomPoll', 'setpointWrite'],
    requiresApprovalActions: [],
    eventCategories: ['climate', 'knxValueUpdated', 'roomUpdated'],
    enabled: true,
    experimental: false,
  },
  {
    domainId: 'lighting',
    category: 'environment',
    displayName: 'Lighting',
    runtimeOwner: 'knx-runtime',
    capabilities: ['readState', 'writeState', 'realtimeEvents', 'persistentHistory', 'polling', 'subscriptions', 'signalLogging'],
    providers: ['knx', 'deltacoTuya'],
    trustedActions: ['roomPoll', 'lightWrite', 'brightnessWrite'],
    requiresApprovalActions: [],
    eventCategories: ['lighting', 'knxValueUpdated', 'roomUpdated'],
    enabled: true,
    experimental: false,
  },
  {
    domainId: 'media',
    category: 'experience',
    displayName: 'Media',
    runtimeOwner: 'media-runtime',
    capabilities: ['readState', 'writeState', 'executeAction', 'realtimeEvents', 'persistentHistory', 'diagnosticsAccess'],
    providers: ['cast', 'sonos'],
    trustedActions: ['mediaPlayback', 'mediaVolume'],
    requiresApprovalActions: [],
    eventCategories: ['media', 'providerStateChanged'],
    enabled: true,
    experimental: false,
  },
  {
    domainId: 'camera',
    category: 'security',
    displayName: 'Camera / NVR',
    runtimeOwner: 'camera-runtime-foundation',
    capabilities: ['readState', 'realtimeEvents', 'persistentHistory', 'diagnosticsAccess', 'liveStream', 'snapshot', 'recording', 'motion', 'offline', 'storage'],
    providers: ['cameraNvr'],
    trustedActions: [],
    requiresApprovalActions: [],
    eventCategories: ['camera', 'recorder', 'storage', 'providerStateChanged'],
    enabled: true,
    experimental: true,
  },
  {
    domainId: 'utility',
    category: 'device',
    displayName: 'Utility',
    runtimeOwner: 'integration-os',
    capabilities: ['readState', 'realtimeEvents', 'persistentHistory', 'polling', 'providerLifecycle', 'diagnosticsAccess'],
    providers: ['dreameCloud', 'homeAssistantBridge', 'deltacoTuya', 'energyMeter'],
    trustedActions: ['roomPoll'],
    requiresApprovalActions: ['providerLifecycle'],
    eventCategories: ['vacuum', 'deltacoTuya', 'energy', 'providerStateChanged'],
    enabled: true,
    experimental: true,
  },
  {
    domainId: 'security',
    category: 'governance',
    displayName: 'Security',
    runtimeOwner: 'runtime-governance',
    capabilities: ['proposeAction', 'diagnosticsAccess', 'persistentHistory'],
    providers: [],
    trustedActions: [],
    requiresApprovalActions: ['insightSuggestion', 'providerLifecycle'],
    eventCategories: ['runtimeAction', 'runtimeIdentity'],
    enabled: true,
    experimental: true,
  },
  {
    domainId: 'integration',
    category: 'integration',
    displayName: 'Integration OS',
    runtimeOwner: 'integration-manager',
    capabilities: ['readState', 'providerLifecycle', 'diagnosticsAccess', 'polling', 'realtimeEvents'],
    providers: ['dreameCloud', 'homeAssistantBridge', 'cast', 'mqtt', 'deltacoTuya', 'energyMeter', 'sonos', 'deco', 'mill', 'namron'],
    trustedActions: [],
    requiresApprovalActions: ['providerLifecycle'],
    eventCategories: ['providerStateChanged', 'integration'],
    enabled: true,
    experimental: false,
  },
  {
    domainId: 'runtime',
    category: 'runtime',
    displayName: 'Runtime Bus',
    runtimeOwner: 'bridge-runtime',
    capabilities: ['readState', 'realtimeEvents', 'persistentHistory', 'polling', 'diagnosticsAccess'],
    providers: ['bridge'],
    trustedActions: ['runtimeConfigRefresh'],
    requiresApprovalActions: [],
    eventCategories: ['runtime', 'runtimeAction', 'runtimeIdentity'],
    enabled: true,
    experimental: false,
  },
  {
    domainId: 'diagnostics',
    category: 'diagnostics',
    displayName: 'Diagnostics',
    runtimeOwner: 'manager-diagnostics',
    capabilities: ['readState', 'diagnosticsAccess', 'signalLogging', 'persistentHistory'],
    providers: ['bridge', 'knx', 'mqtt', 'energyMeter'],
    trustedActions: ['roomPoll'],
    requiresApprovalActions: [],
    eventCategories: ['diagnostics', 'signalLoggerPoint'],
    enabled: true,
    experimental: true,
  },
]

export function createRuntimeDomainSnapshot({ healthResolver = () => 'healthy' } = {}) {
  const domains = runtimeDomainDefinitions.map((domain) => {
    const sensitiveCapabilities = domain.capabilities.filter((capability) =>
      sensitiveRuntimeCapabilities.has(capability),
    )
    return {
      ...domain,
      health: healthResolver(domain),
      sensitiveCapabilities,
      approvalHeavy: domain.requiresApprovalActions.length > 0,
      realtimeCritical: domain.capabilities.includes('realtimeEvents'),
    }
  })

  return {
    model: 'runtime-domain-foundation',
    microservices: false,
    pluginSystem: false,
    distributedRuntime: false,
    domains,
    counts: {
      domains: domains.length,
      enabled: domains.filter((domain) => domain.enabled).length,
      experimental: domains.filter((domain) => domain.experimental).length,
      approvalSensitive: domains.filter((domain) => domain.approvalHeavy).length,
      realtimeCapable: domains.filter((domain) => domain.realtimeCritical).length,
    },
    sensitiveCapabilities: Array.from(sensitiveRuntimeCapabilities),
  }
}
